import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import giffTest from '@/public/2.gif'
import Image from 'next/image';


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className=''>
      <body className='h-screen flex flex-col'>
        {children}
        <Image
          src={giffTest} 
          alt="my gif" 
          height={500}
          width={500}
          className='w-screen h-screen absolute top-0 left-0 z-0 object-cover'
        />
      </body>
    </html>
  )
}
