import { ThemeProvider } from './components/providers/theme'
import { allFontVariables } from './fonts'
import './globals.css'
import "slick-carousel/slick/slick.css"; 
import "slick-carousel/slick/slick-theme.css";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={allFontVariables}>
      <body className='h-screen flex flex-col'>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  )
}
