import { ThemeProvider } from './components/providers/theme'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className=''>
      <body className='h-screen flex flex-col'>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  )
}
