export { ClockColorPicker } from './clock-colorpicker'
export { ClockItalic } from './clock-italic'
export { ClockBold } from './clock-bold'
export { ClockFontSize } from './clock-fontsize'
export { ClockAlignment } from './clock-alignment'